import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NextUIProviders } from "@/providers/NextUIProvider";
import NavBar from "@/components/Navbar";
import { MaterialTailwindProvider } from "@/providers/MaterialTailwindProvider";
import Footer from "@/components/Footer";
import { StoreProvider } from "@/providers/storeProvider";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ahaz | Pharma",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-primary/40 ${inter.className}`}>
        <StoreProvider>
          <NextUIProviders>
            <MaterialTailwindProvider>
              <Toaster toastOptions={{ duration: 5000 }} />

              {children}
            </MaterialTailwindProvider>
          </NextUIProviders>
        </StoreProvider>
      </body>
    </html>
  );
}
